model_selection:
  models:
    LinearRegression():
      class: LinearRegression
      module: sklearn.linear_model
      search_params:
        n_neighbours:
          - 3
          - 5
          - 7
          - 9
        normalize: 
          - True
          - False
    Ridge():
      class: Ridge
      module: sklearn.linear_model
      search_params:
        n_neighbors:
          - 3
          - 5
          - 7
          - 9
        alpha:
          - 0.01
          - 0.1
          - 1
          - 10
    Lasso():
      class: Lasso
      module: sklearn.linear_model
      search_params:
        n_neighbors:
          - 3
          - 5
          - 7
          - 9
        alpha:
          - 0.001
          - 0.01
          - 0.1
          - 1
          - 10
          - 100
          - 1000
    ElasticNet():
      class: ElasticNet
      module: sklearn.linear_model
      search_params:
        alpha:
          - 0.001
          - 0.01
          - 0.1
          - 1
          - 10
          - 100
          - 1000 
    DecisionTreeRegressor():
      class: DecisionTreeRegressor
      module: sklearn.tree
      search_params:
        criterion:
          - squared_error
          - absolute_error        
    RandomForestRegressor():
      class: RandomForestRegressor
      module: sklearn.ensemble
      search_params:
        n_estimators:
          - 10
          - 20
          - 30
          - 50
        max_depth:
          - 10
          - 15
          - 20
          - 25
        criterion:
          - squared_error
          - absolute_error
    SVR():
      class: SVR
      module: sklearn.svm
      search_params:
        kernel:
          - rbf
          - linear
        degree: 
          - 1
          - 2
          - 3
          - 4
          - 5